import logging
import subprocess
import tempfile
from pathlib import Path
from io import BytesIO
from typing import TYPE_CHECKING, List

if TYPE_CHECKING:
    from report_check.parser.models import ReportData
    from report_check.storage.artifacts import CheckArtifact

logger = logging.getLogger(__name__)


class ReportRenderer:
    """Render reports as images for multimodal analysis."""

    async def render(self, report_data: "ReportData", artifacts: "CheckArtifact | None" = None) -> List[bytes]:
        """Render report to images.

        Args:
            report_data: Report data to render
            artifacts: Optional artifacts manager for saving rendered images

        Returns:
            List of image bytes (one per page)
        """
        if report_data.source_type == "pdf":
            return await self._render_pdf(report_data, artifacts)
        elif report_data.source_type == "excel":
            return await self._render_excel(report_data, artifacts)
        else:
            logger.error(f"Unsupported source type: {report_data.source_type}")
            return []

    async def _render_pdf(self, report_data: "ReportData", artifacts: "CheckArtifact | None") -> List[bytes]:
        """Render PDF pages as images."""
        images = []

        # Check if we already have page images from parsing
        if hasattr(report_data, 'page_images') and report_data.page_images:
            for page_num, img_data in report_data.page_images.items():
                images.append(img_data)
                if artifacts:
                    artifacts.add_image_evidence(f"page_{page_num}", img_data, "png")
            return images

        # Otherwise render from PDF file
        import fitz  # PyMuPDF

        pdf_path = report_data.metadata.get("file_path")
        if not pdf_path:
            return []

        doc = fitz.open(pdf_path)
        for page_num in range(len(doc)):
            page = doc[page_num]
            pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))  # 2x scale
            img_data = pix.tobytes("png")
            images.append(img_data)

            if artifacts:
                artifacts.add_image_evidence(f"page_{page_num+1}", img_data, "png")

        doc.close()
        return images

    async def _render_excel(self, report_data: "ReportData", artifacts: "CheckArtifact | None") -> List[bytes]:
        """Render Excel as image. Tries LibreOffice first, falls back to PIL."""
        excel_path = report_data.metadata.get("file_path")
        if not excel_path:
            return []

        if not Path(excel_path).exists():
            logger.warning(f"Excel file not found: {excel_path}")
            return []

        # Try LibreOffice first for better quality
        try:
            return await self._render_excel_with_libreoffice(report_data, artifacts)
        except Exception as e:
            logger.warning(f"LibreOffice rendering failed: {e}, falling back to PIL")
            return await self._render_excel_with_pil(report_data, artifacts)

    async def _render_excel_with_libreoffice(self, report_data: "ReportData", artifacts: "CheckArtifact | None") -> List[bytes]:
        """Render Excel using LibreOffice: Excel -> PDF -> Images."""
        import fitz  # PyMuPDF

        excel_path = Path(report_data.metadata.get("file_path", ""))

        with tempfile.TemporaryDirectory() as tmpdir:
            # Convert Excel to PDF using LibreOffice
            cmd = [
                "soffice",
                "--headless",
                "--convert-to", "pdf",
                "--outdir", tmpdir,
                str(excel_path)
            ]

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

            if result.returncode != 0:
                raise RuntimeError(f"LibreOffice conversion failed: {result.stderr}")

            pdf_path = Path(tmpdir) / f"{excel_path.stem}.pdf"
            if not pdf_path.exists():
                raise FileNotFoundError(f"PDF not generated by LibreOffice")

            # Render PDF pages as images
            images = []
            doc = fitz.open(str(pdf_path))

            for page_num in range(len(doc)):
                page = doc[page_num]
                pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))  # 2x scale for better quality
                img_data = pix.tobytes("png")
                images.append(img_data)

                if artifacts:
                    artifacts.add_image_evidence(f"sheet_{page_num+1}", img_data, "png")

            doc.close()
            logger.info(f"LibreOffice rendered {len(images)} pages from Excel")
            return images

    async def _render_excel_with_pil(self, report_data: "ReportData", artifacts: "CheckArtifact | None") -> List[bytes]:
        """Render Excel as image with embedded images pasted at anchor positions (fallback)."""
        from openpyxl import load_workbook
        from PIL import Image, ImageDraw, ImageFont

        excel_path = report_data.metadata.get("file_path")
        if not excel_path:
            return []

        if not Path(excel_path).exists():
            logger.warning(f"Excel file not found: {excel_path}")
            return []

        try:
            wb = load_workbook(excel_path)
        except Exception as e:
            logger.error(f"Failed to load Excel file: {e}")
            return []

        # Group images by anchor row
        img_by_row: dict[int, list] = {}
        for img_item in report_data.images:
            row = img_item.anchor.get("row", 0)
            img_by_row.setdefault(row, []).append(img_item)

        # Layout constants - optimized for readability
        MARGIN = 20
        CANVAS_WIDTH = 1600  # Slightly smaller for better text readability
        ROW_HEIGHT = 36  # Increased for better spacing
        FONT_SIZE = 18
        IMAGE_MAX_HEIGHT = 500  # Larger images
        IMAGE_MAX_WIDTH = CANVAS_WIDTH - 2 * MARGIN

        # Load a font with Chinese support
        font = None
        font_paths = [
            # macOS Chinese fonts
            ("/System/Library/AssetsV2/com_apple_MobileAsset_Font8/86ba2c91f017a3749571a82f2c6d890ac7ffb2fb.asset/AssetData/PingFang.ttc", 0),
            ("/System/Library/Fonts/STHeiti Medium.ttc", 0),
            ("/System/Library/AssetsV2/com_apple_MobileAsset_Font8/862669affb9c2df6a5af4627f6e8c4496e643d6e.asset/AssetData/Hiragino_Sans_TC.ttc", 0),
            ("/System/Library/Fonts/Supplemental/Arial Unicode.ttf", 0),
            # Linux Chinese fonts
            ("/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc", 0),
            ("/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc", 0),
        ]

        for font_path, index in font_paths:
            try:
                font = ImageFont.truetype(font_path, FONT_SIZE, index=index)
                break
            except Exception:
                continue

        if font is None:
            logger.warning("No Chinese font found, using default (may not display Chinese characters)")
            font = ImageFont.load_default()

        sheet_name = report_data.metadata.get("sheet_name")
        result_images = []

        for sheet in wb.worksheets:
            max_row = sheet.max_row or 1

            # First pass: calculate total canvas height
            total_height = MARGIN
            for row_num in range(1, max_row + 1):
                total_height += ROW_HEIGHT
                if row_num in img_by_row:
                    for img_item in img_by_row[row_num]:
                        try:
                            pil_img = Image.open(BytesIO(img_item.data))
                            w, h = pil_img.size
                            ratio = min(
                                IMAGE_MAX_WIDTH / w,
                                IMAGE_MAX_HEIGHT / h,
                                2.0,  # Allow up to 2x upscaling
                            )
                            total_height += int(h * ratio) + 15
                        except Exception:
                            pass
            total_height += MARGIN

            # Create canvas
            canvas = Image.new("RGB", (CANVAS_WIDTH, max(total_height, 500)), "white")
            draw = ImageDraw.Draw(canvas)

            # Second pass: draw text and images
            y = MARGIN
            for row in sheet.iter_rows(min_row=1, max_row=max_row):
                row_num = row[0].row

                # Draw row number for reference
                draw.text((5, y), f"{row_num:3d}", fill="#888888", font=font)

                # Draw cell text
                cells = []
                for cell in row:
                    if cell.value is not None:
                        val = str(cell.value).strip()
                        if val:
                            cells.append(val)

                if cells:
                    text = "  |  ".join(cells)
                    # Truncate if too long
                    if len(text) > 200:
                        text = text[:197] + "..."
                    draw.text((MARGIN + 30, y), text, fill="black", font=font)

                y += ROW_HEIGHT

                # Paste images anchored at this row (only on the matching sheet)
                if row_num in img_by_row and sheet.title == sheet_name:
                    for img_item in img_by_row[row_num]:
                        try:
                            pil_img = Image.open(BytesIO(img_item.data))
                            w, h = pil_img.size
                            ratio = min(
                                IMAGE_MAX_WIDTH / w,
                                IMAGE_MAX_HEIGHT / h,
                                2.0,  # Allow up to 2x upscaling
                            )
                            new_w = int(w * ratio)
                            new_h = int(h * ratio)
                            if ratio != 1.0:
                                pil_img = pil_img.resize((new_w, new_h), Image.LANCZOS)

                            # Expand canvas if image overflows
                            needed = y + new_h + MARGIN
                            if needed > canvas.height:
                                new_canvas = Image.new(
                                    "RGB", (CANVAS_WIDTH, needed + MARGIN), "white"
                                )
                                new_canvas.paste(canvas)
                                canvas = new_canvas
                                draw = ImageDraw.Draw(canvas)

                            # Draw a light border around image
                            canvas.paste(pil_img, (MARGIN + 30, y))
                            draw.rectangle(
                                [(MARGIN + 30 - 2, y - 2), (MARGIN + 30 + new_w + 2, y + new_h + 2)],
                                outline="#cccccc",
                                width=1
                            )

                            # Add image label
                            label = f"[{img_item.id}]"
                            draw.text((MARGIN + 30, y + new_h + 3), label, fill="#666666", font=font)

                            y += new_h + 25
                        except Exception as e:
                            logger.warning(f"Failed to render image at row {row_num}: {e}")

            # Crop to content
            bbox = canvas.getbbox()
            if bbox:
                canvas = canvas.crop(bbox)

            buf = BytesIO()
            canvas.save(buf, format="PNG")
            page_data = buf.getvalue()
            result_images.append(page_data)

            if artifacts:
                artifacts.add_image_evidence(f"sheet_{sheet.title}", page_data, "png")

        return result_images
